version: '3.8'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    volumes:
      - ./front-end:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - app-network

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    volumes:
      - ./back-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=task_db
    ports:
      - "5431:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
